In [1]:
import pandas as pd

In [3]:
s = pd.Series([1,2,3,4])
s

0    1
1    2
2    3
3    4
dtype: int64

In [4]:
s = pd.Series([1,2,3,4] , index = ["a","b","c","d"])
s

a    1
b    2
c    3
d    4
dtype: int64

In [5]:
data = [[1,444,'abc'],
        [2,555,'def'],
        [3,666,'ghi'],
        [4,444,'xyz']
]

df = pd.DataFrame(data , columns=['id' , 'salary' , 'dep'])
df

id  salary  dep
0   1     444  abc
1   2     555  def
2   3     666  ghi
3   4     444  xyz

In [33]:
data_dictionary = {'id':[1,2,3],
            'salary':[444,555,666],
            'dept':['abc','def','xyz']
}

df = pd.DataFrame(data_dictionary)
display(df)

id  salary dept
0   1     444  abc
1   2     555  def
2   3     666  xyz

In [34]:
x = df.columns
index = ['R1','R2','R3']
df.index = index

df

id  salary dept
R1   1     444  abc
R2   2     555  def
R3   3     666  xyz

In [8]:
df.dtypes

id        int64
salary    int64
dept        str
dtype: object

In [9]:
df['dept'].dtype

<StringDtype(storage='python', na_value=nan)>

In [10]:
def chk(df,ty):
    return df[ty].dtype 

In [11]:
chk(df , 'id')

dtype('int64')

In [12]:
df['dept'] = df['dept'].astype('category')

In [13]:
df.dtypes

id           int64
salary       int64
dept      category
dtype: object

In [14]:
chk(df , 'dept')

CategoricalDtype(categories=['abc', 'def', 'xyz'], ordered=False, categories_dtype=str)

Exploratory Data Analysis (EDA)

In [15]:
df.head(2)

id  salary dept
R1   1     444  abc
R2   2     555  def

In [16]:
df.tail(2)

id  salary dept
R2   2     555  def
R3   3     666  xyz

In [17]:
df.describe()

id  salary
count  3.0     3.0
mean   2.0   555.0
std    1.0   111.0
min    1.0   444.0
25%    1.5   499.5
50%    2.0   555.0
75%    2.5   610.5
max    3.0   666.0

In [18]:
df.describe(include='category')

dept
count     3
unique    3
top     abc
freq      1

In [19]:
df.index

Index(['R1', 'R2', 'R3'], dtype='str')

In [20]:
df.columns

Index(['id', 'salary', 'dept'], dtype='str')

In [21]:
print(df['salary'].unique())

[444 555 666]


In [22]:
print(sum(df['salary'].unique()))

1665


In [23]:
df['salary'].nunique()

3

In [24]:
df['salary'].min()

np.int64(444)

In [25]:
df.info()

<class 'pandas.DataFrame'>
Index: 3 entries, R1 to R3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   id      3 non-null      int64   
 1   salary  3 non-null      int64   
 2   dept    3 non-null      category
dtypes: category(1), int64(2)
memory usage: 207.0+ bytes


In [26]:
df.infer_objects()

id  salary dept
R1   1     444  abc
R2   2     555  def
R3   3     666  xyz

In [27]:
df['salary'].sum()

np.int64(1665)

In [28]:
df['salary'].values

array([444, 555, 666])

In [35]:
df.values

array([[1, 444, 'abc'],
       [2, 555, 'def'],
       [3, 666, 'xyz']], dtype=object)

In [30]:
# df.replace('Hazem',555 , inplace=True)

In [31]:
df

id  salary dept
R1   1     444  abc
R2   2     555  def
R3   3     666  xyz

In [36]:
df.replace({444:"Ali", "abc":555})

id salary dept
R1   1    Ali  555
R2   2    555  def
R3   3    666  xyz

In [ ]:
x = df['salary'].iloc[2]
x

np.int64(666)

In [ ]:
df.iloc[2,1]

np.int64(666)

In [ ]:
df.iloc[:]

id  salary dept
R1   1     444  abc
R2   2     555  def
R3   3     666  xyz

In [ ]:
df.iloc[: , 0:2]

id  salary
R1   1     444
R2   2     555
R3   3     666

In [ ]:
import numpy as np
import pandas as pd

data = [
    [1, 444, 'abc'],
    [np.nan, 555, 'def'],
    [3, 666, 'ghi'],
    [4, np.nan, 'xyz']
]

df = pd.DataFrame(data, columns=['id', 'salary', 'dept'])
df


id  salary dept
0  1.0   444.0  abc
1  NaN   555.0  def
2  3.0   666.0  ghi
3  4.0     NaN  xyz

In [ ]:
null = df.isnull().sum()
null

id        1
salary    1
dept      0
dtype: int64

In [ ]:
pd.DataFrame(null).T


id  salary  dept
0   1       1     0

In [ ]:
df.dropna()

id  salary dept
0  1.0   444.0  abc
2  3.0   666.0  ghi

In [ ]:
df.dropna(subset=['salary'])

id  salary dept
0  1.0   444.0  abc
1  NaN   555.0  def
2  3.0   666.0  ghi

In [ ]:
df.dropna(axis=1)

dept
0  abc
1  def
2  ghi
3  xyz

In [ ]:
df.drop(['id'] , axis = 1)

salary dept
0   444.0  abc
1   555.0  def
2   666.0  ghi
3     NaN  xyz

In [ ]:
mean = df['salary'].mean()


In [ ]:
df['salary'] = df['salary'].fillna(mean)
df

id  salary dept
0  1.0   444.0  abc
1  NaN   555.0  def
2  3.0   666.0  ghi
3  4.0   555.0  xyz

In [ ]:
Header_col = ['index' , 'Age' , 'gender' , 'Department' , 'Postal code']
data=pd.read_table('http://bit.ly/movieusers' , sep='|' , header = None , names=Header_col)
data.head()

index  Age gender  Department Postal code
0      1   24      M  technician       85711
1      2   53      F       other       94043
2      3   23      M      writer       32067
3      4   24      M  technician       43537
4      5   33      F       other       15213

In [ ]:
user_info=pd.read_csv('http://bit.ly/uforeports')
user_info.head()

City Colors Reported Shape Reported State             Time
0                Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00
1           Willingboro             NaN          OTHER    NJ  6/30/1930 20:00
2               Holyoke             NaN           OVAL    CO  2/15/1931 14:00
3               Abilene             NaN           DISK    KS   6/1/1931 13:00
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00

In [ ]:
user_info['Location'] = user_info.City +' '+ user_info.State
user_info.head()

City Colors Reported Shape Reported State             Time  \
0                Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00   
1           Willingboro             NaN          OTHER    NJ  6/30/1930 20:00   
2               Holyoke             NaN           OVAL    CO  2/15/1931 14:00   
3               Abilene             NaN           DISK    KS   6/1/1931 13:00   
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00   

                  Location  
0                Ithaca NY  
1           Willingboro NJ  
2               Holyoke CO  
3               Abilene KS  
4  New York Worlds Fair NY

In [ ]:
user_info.to_csv('test_csv')

In [ ]:
user_info.rename(columns={"Colors Reported" : "Colors_Reported"})

City Colors_Reported Shape Reported State  \
0                    Ithaca             NaN       TRIANGLE    NY   
1               Willingboro             NaN          OTHER    NJ   
2                   Holyoke             NaN           OVAL    CO   
3                   Abilene             NaN           DISK    KS   
4      New York Worlds Fair             NaN          LIGHT    NY   
...                     ...             ...            ...   ...   
18236            Grant Park             NaN       TRIANGLE    IL   
18237           Spirit Lake             NaN           DISK    IA   
18238           Eagle River             NaN            NaN    WI   
18239           Eagle River             RED          LIGHT    WI   
18240                  Ybor             NaN           OVAL    FL   

                   Time                 Location  
0        6/1/1930 22:00                Ithaca NY  
1       6/30/1930 20:00           Willingboro NJ  
2       2/15/1931 14:00               Holyoke CO  
3        6/1/1931 13:00               Abilene KS  
4       4/18/1933 19:00  New York Worlds Fair NY  
...                 ...                      ...  
18236  12/31/2000 23:00            Grant Park IL  
18237  12/31/2000 23:00           Spirit Lake IA  
18238  12/31/2000 23:45           Eagle River WI  
18239  12/31/2000 23:45           Eagle River WI  
18240  12/31/2000 23:59                  Ybor FL  

[18241 rows x 6 columns]

In [ ]:
user_info.columns = user_info.columns.str.replace(" " , "_")
user_info.head()

City Colors_Reported Shape_Reported State             Time  \
0                Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00   
1           Willingboro             NaN          OTHER    NJ  6/30/1930 20:00   
2               Holyoke             NaN           OVAL    CO  2/15/1931 14:00   
3               Abilene             NaN           DISK    KS   6/1/1931 13:00   
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00   

                  Location  
0                Ithaca NY  
1           Willingboro NJ  
2               Holyoke CO  
3               Abilene KS  
4  New York Worlds Fair NY

In [ ]:
user_info.drop(columns=['City' ,'State'])
user_info.head()

City Colors_Reported Shape_Reported State             Time  \
0                Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00   
1           Willingboro             NaN          OTHER    NJ  6/30/1930 20:00   
2               Holyoke             NaN           OVAL    CO  2/15/1931 14:00   
3               Abilene             NaN           DISK    KS   6/1/1931 13:00   
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00   

                  Location  
0                Ithaca NY  
1           Willingboro NJ  
2               Holyoke CO  
3               Abilene KS  
4  New York Worlds Fair NY