In [2]:
import numpy as np

In [18]:
v1 = np.array([10,6,7])
v2 = np.array([20,3,3])


print(v1+v2)
print(type(v1))
print(v1.ndim)
print(v1.shape)

[30  9 10]
<class 'numpy.ndarray'>
1
(3,)


In [11]:
print(v1.dot(v2))

239


In [ ]:
m1 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print(m1.ndim)
print(m1.shape)

2
(3, 3)


In [23]:
vec = np.array([1,2,3,4,5,6])
mat = vec.reshape((3,2))
print(mat)


[[1 2]
 [3 4]
 [5 6]]


In [25]:
vec = np.array([1,2,3,4])
vec.shape[0]

4

In [30]:
mat = vec.reshape((vec.shape[0],1))
mat

array([[1],
       [2],
       [3],
       [4]])

In [31]:
vec = np.array([1,2,3,4])
mat = vec[ : , None]
mat

array([[1],
       [2],
       [3],
       [4]])

In [35]:
mat = np.array([[1,2,3],
                [4,True,6],
                [7,8,9.0]])
#object--->string--->float--->int--->boolian
mat.dtype

dtype('float64')

In [38]:
class C:
    x = 3

c1 = C()

In [42]:
mat = np.array([[c1 , 8 ],
                [3,2]])

mat.dtype

dtype('O')

In [49]:
mat = np.array([[1,2,3],
                [4,"5",6],
                [7,8,9]])

float_matrix = mat.astype(float)
print(float_matrix.dtype)
print(float_matrix)

float64
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [4]:
v = np.array ([2,3,2,4,3,5,6])
v[2:5]


array([2, 4, 3])

In [10]:
mat = np.array([[1,2,3],
                [4,5,6],
                [7,8,9],
                [0,0,0]])

print(mat[-3:-1 , -3:-1])

[[4 5]
 [7 8]]


In [11]:
angle = np.arange(0 , 361 , 90)
angle

array([  0,  90, 180, 270, 360])

In [17]:
I = np.identity(3 , dtype='int')
I

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [19]:
np.random.random((3,3))

array([[0.61510418, 0.10787652, 0.65535839],
       [0.22673634, 0.51273871, 0.55264824],
       [0.08875466, 0.97861331, 0.51480989]])

In [23]:
a = ['ali' , 3 , 'hazem' , False]
np.random.choice(a , size=(3,5))


array([['ali', '3', '3', 'hazem', 'hazem'],
       ['False', '3', 'ali', '3', 'ali'],
       ['ali', '3', '3', 'hazem', 'ali']], dtype='<U21')

In [27]:
mat_1 = np.zeros((3,4))
mat_2 = np.ones((5,3))

np.savez('np_file' , Ones_Mat = mat_1 , Zeros_Mat = mat_2)



In [29]:
with np.load('np_file.npz') as file:
    mat_1 = file['Ones_Mat']
    mat_2 = file['Zeros_Mat']

print(mat_1)
print(mat_2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [31]:
def array_reshape ( arr , rows = -1 , col = -1):

    try:
        arr = np.array(arr)
        return arr.reshape(rows , col)
    except (TypeError , ValueError) as e:
        raise ValueError(f'Invalid reshape operation:{e}')
    


In [33]:
vec = [1,2,3,4,5,6]
print(array_reshape(vec , 2, 3))

[[1 2 3]
 [4 5 6]]


In [34]:
v = np.array([1,2,3,4,5,0])
np.any(v >= 1)

np.True_

In [35]:
v = np.array([1,2,3,4,5,0])
np.all(v >= 1)

np.False_

In [ ]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([1,8,0,6,5])

np.isclose(v1,v2)

array([ True, False, False, False,  True])

In [38]:
v = np.array([2,3,5,4,10])

condition = v >= 4
print(condition)

[False False  True  True  True]


In [40]:
v = np.array([2,3,5,4,10])
condition = v >= 4
new_arr = np.where(condition , -1 , v)
print(new_arr)

[ 2  3 -1 -1 -1]
