In [3]:
import numpy as np

In [18]:
v1 = np.array([10,6,7])
v2 = np.array([20,3,3])


print(v1+v2)
print(type(v1))
print(v1.ndim)
print(v1.shape)

[30  9 10]
<class 'numpy.ndarray'>
1
(3,)


In [11]:
print(v1.dot(v2))

239


In [ ]:
m1 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print(m1.ndim)
print(m1.shape)

2
(3, 3)


In [23]:
vec = np.array([1,2,3,4,5,6])
mat = vec.reshape((3,2))
print(mat)


[[1 2]
 [3 4]
 [5 6]]


In [25]:
vec = np.array([1,2,3,4])
vec.shape[0]

4

In [30]:
mat = vec.reshape((vec.shape[0],1))
mat

array([[1],
       [2],
       [3],
       [4]])

In [31]:
vec = np.array([1,2,3,4])
mat = vec[ : , None]
mat

array([[1],
       [2],
       [3],
       [4]])

In [35]:
mat = np.array([[1,2,3],
                [4,True,6],
                [7,8,9.0]])
#object--->string--->float--->int--->boolian
mat.dtype

dtype('float64')

In [38]:
class C:
    x = 3

c1 = C()

In [42]:
mat = np.array([[c1 , 8 ],
                [3,2]])

mat.dtype

dtype('O')

In [49]:
mat = np.array([[1,2,3],
                [4,"5",6],
                [7,8,9]])

float_matrix = mat.astype(float)
print(float_matrix.dtype)
print(float_matrix)

float64
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
